name: Build and deploy Node.js app to Azure Web App - techcenterperu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Xvfb (X virtual framebuffer)
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1280x1024x24 &

      - name: Check Xvfb process
        run: |
          ps aux | grep Xvfb

      - name: Set display environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Display Environment Variable
        run: echo $DISPLAY

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --browsers ChromeHeadlessCI --singleRun --if-present || exit 0 # Asegura que las pruebas finalicen correctamente

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'techcenterperu'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F0A3C9073BDB466590AE9C8139348D68 }}
          package: .
